---
- hosts: localhost
  gather_facts: true
  tasks:
    #Update apt
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
    #Install and Update MySQL
    - name: Update apt and install Mysql
      apt:
        name: mariadb
        state: latest
        update_cache: true    
